#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys

LONG_P = """\
<p>
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames
    ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
    tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
    ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et
    sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo
    vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
    condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
    Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque
    id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu
    erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor,
    facilisis luctus, metus
</p>"""

MED_P = """\
<p>
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames
    ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
    tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.
    Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
</p>"""

P = """\
<p>
    Pellentesque habitant morbi tristique senectus et netus et malesuada fames
    ac turpis egestas.
</p>"""

DL = """\
<dl>
    <dt>Definition list</dt>
    <dd>
        Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </dd>
    <dt>Lorem ipsum dolor sit amet</dt>
    <dd>
        Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
        labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </dd>
</dl>"""

L_UL = """\
<ul>
    <li>
        Morbi in sem quis dui placerat ornare. Pellentesque odio nisi, euismod
        in, pharetra a, ultricies in, diam. Sed arcu. Cras consequat.
    </li>
    <li>
        Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue,
        eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi,
        tincidunt quis, accumsan porttitor, facilisis luctus, metus.
    </li>
    <li>
        Phasellus ultrices nulla quis nibh. Quisque a lectus. Donec
        consectetuer ligula vulputate sem tristique cursus. Nam nulla quam,
        gravida non, commodo a, sodales sit amet, nisi.
    </li>
    <li>
        Pellentesque fermentum dolor. Aliquam quam lectus, facilisis auctor,
        ultrices ut, elementum vulputate, nunc.
    </li>
</ul>"""

UL = """\
<ul>
    <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
    <li>Aliquam tincidunt mauris eu risus.</li>
    <li>Vestibulum auctor dapibus neque.</li>
</ul>"""

OL = """\
<ol>
    <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
    <li>Aliquam tincidunt mauris eu risus.</li>
    <li>Vestibulum auctor dapibus neque.</li>
</ol>"""

UL_NAV = """\
<nav>
    <ul>
        <li><a href="#nowhere" title="Lorum ipsum dolor sit amet">Lorem</a></li>
        <li><a href="#nowhere" title="Aliquam tincidunt mauris eu risus">Aliquam</a></li>
        <li><a href="#nowhere" title="Morbi in sem quis dui placerat ornare">Morbi</a></li>
        <li><a href="#nowhere" title="Praesent dapibus, neque id cursus faucibus">Praesent</a></li>
        <li><a href="#nowhere" title="Pellentesque fermentum dolor">Pellentesque</a></li>
    </ul>
</nav>"""


TEXTS = {'lp': LONG_P, 'mp': MED_P, 'p': P, 'lul': L_UL, 'ul': UL, 'ol': OL,
         'uln': UL_NAV, 'dl': DL}


def main(argv=None):
    """docstring for main"""
    if argv is None:
        argv = sys.argv
    try:
        option = argv[1]
    except (IndexError, KeyError):
        option = 'mp'
    print TEXTS[option]
    return


if __name__ == '__main__':
    sys.exit(main())
